---
# tasks file for testrun
- name: checkout projCert source
  git:
    repo: https://github.com/priteshkumar/projcert.git
    dest: /home/jenkins/workspace/projcert
    version: master
- name: get head sha1
  shell: git rev-parse --short HEAD
  args:
    chdir: /home/jenkins/workspace/projcert
  register: cmd_output
- debug:
    var: cmd_output
- name: build webapp docker image
  docker_image:
    state: present
    path: /home/jenkins/workspace/projcert
    name: mavpks/eduwebapp
    tag: '{{ cmd_output.stdout }}'
- name: run webapp docker container
  docker_container:
    name: eduwebapp
    image: "mavpks/eduwebapp:{{ cmd_output.stdout }}"
    ports:
      - "3000:80"
- name: check webapp
  shell: curl localhost:3000
  register: webhome
  ignore_errors: yes
- name: list docker webapp container
  shell: docker ps
  register: webd
- debug:
    var: webd
- debug:
    var: webhome
- name: configure xvfb for selenium
  shell: Xvfb :99 &
  register: xvfbpid
- debug:
    var: xvfbpid
- name: set display env
  shell: export DISPLAY=:99
- name: echo env
  shell: echo $DISPLAY
  register: envars
- debug:
    var: envars
- name: set docker imgtag
  shell: echo '{{ cmd_output.stdout }}' >> imgtag.txt
  args:
    chdir: /home/jenkins/workspace/projcert/tests
- name: run selenium tests
  shell: python Seleniumtest.py
  args:
    chdir: /home/jenkins/workspace/projcert/tests
  register: testout
- debug:
    var: testout
- include_tasks: dumpresults.yml
- name: archieve test results
  archive:
    path:
      - /home/jenkins/workspace/projcert/tests/*.png
      - /home/jenkins/workspace/projcert/tests/*.xml
      - /home/jenkins/workspace/projcert/tests/imgtag.txt
      - /home/jenkins/workspace/projcert/tests/teststatus.txt
    dest: /home/jenkins/workspace/projcert/testresult.gz
    format: gz
- name: check test status
  shell: cat /home/jenkins/workspace/projcert/tests/teststatus.txt
  register: teststatus
- debug:
    var: teststatus
- name: push eduwebapp image to docker hub
  docker_image:
    name: mavpks/eduwebapp
    tag: '{{ cmd_output.stdout }}'
    push: yes
- name: fetch test results
  fetch:
    src: /home/jenkins/workspace/projcert/testresult.gz
    dest: /var/lib/jenkins/jobs/pipelines/jobs/projCert/workspace/
    flat: yes
